---
- hosts: local
  remote_user: root
  vars:
    SUPER_VAR: "VARIABLE"
#  become: true
  tasks:  
#  - name: Installing nginx
#    apt: pkg=nginx state=installed
  - name: Install updated file
    template: src=templates/index.template dest=/usr/share/nginx/html/index.html mode=0655
#  - name: starting nginx
#    service: name=nginx state=started
