---
- hosts: local
  remote_user: root
#  become: true
  tasks:  
  - name: Installing nginx
    apt: pkg=ngnix state=installed mode=0655
  - name: Install updated file
    template: src=templates/index.template dst=/usr/share/nginx/html/index.html
  - name: starting nginx
    service: name=nginx state=started
