---
- hosts: local
  remote_user: root
#  become: true
  tasks:  
  - name: Install mc
    apt:
      name: mc 
      state: present
      force: yes
      update_cache: yes
      install_recommends: yes
#  - name: start nginx
#    service: 
#      name: nginx
#      state: started
